management:
  info:
    git:
      mode: full
security:
  user: 
    password: password

dockercloud:
  rest:
    host: https://cloud.docker.com
  service:
    api:
      uri: /api/app/v1/stumacsolutions/service/6e41c4e5-f781-46cb-95cb-1c1d034fb2d3/